# Generated by Django 4.2.1 on 2023-05-15 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('just_text', models.CharField(max_length=255, verbose_name='Just a field')),
            ],
        ),
    ]
