# Generated by Django 4.2.1 on 2023-05-17 06:34

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0004_alter_account_balance_alter_account_balance_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='balance_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR'), ('USD', 'USD')], default='CZK', editable=False, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR'), ('USD', 'USD')], default=None, editable=False, max_length=3),
        ),
    ]
