# Generated by Django 4.2.1 on 2023-05-17 06:49

from django.db import migrations
import djmoney.models.fields


def add_sample_data(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    SimpleModel = apps.get_model('bank', 'SimpleModel')
    SimpleModel.objects.create(just_text="Text 1")
    SimpleModel.objects.create(just_text="Text 2")


class Migration(migrations.Migration):
    dependencies = [
        ('bank', '0005_alter_account_balance_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='balance_currency',
            field=djmoney.models.fields.CurrencyField(
                choices=[('GBP', 'British Pound'), ('CNY', 'Chinese Yuan'), ('CZK', 'Czech Koruna'), ('EUR', 'Euro'),
                         ('USD', 'US Dollar')], default='CZK', editable=False, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount_currency',
            field=djmoney.models.fields.CurrencyField(
                choices=[('GBP', 'British Pound'), ('CNY', 'Chinese Yuan'), ('CZK', 'Czech Koruna'), ('EUR', 'Euro'),
                         ('USD', 'US Dollar')], default=None, editable=False, max_length=3),
        ),
        migrations.RunPython(add_sample_data),
    ]
